name: Oliver Meredith
highlighter: rouge
exclude: ["node_modules", "gulpfile.js", "package.json", "package-lock.json", ".gitignore"]

# when in development
baseurl: ' '
#when uploading to the wild
# baseurl: '/2019-website-redesign-'
collections: 
  portfolio: 
    output: true